#!/bin/sh

# Install Xcode
# Install Xcode cmd line tools

# Download Zshell,
curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh

# Set as default,
# Make sure OS running our new zsh NOT the one built in,
# Configure chsh for user
# setup oh-my-zsh
# check/set local/bin path
# update /etc/shells path
# check SHELL
# what config exec on new window?
# new instance/tab?
# interactive shell (ssh)
# where to put aliases
# where to put variables
# commit, deploy to dropbox, symlink
# BDD/TDD with bash/zsh?
http://scottlab.ucsc.edu/~wgscott/xtal/wiki/index.php/Make_zsh_your_default_user_shell

